### PR TITLE
Update jsdoc to use {xs, ys} from tf.data.csv

### PR DESCRIPTION
**Pull request by kangyizhang**
This resolves https://github.com/tensorflow/tfjs/issues/1273

Note: this PR should not be merged until we are gonna release new tfjs-data and tfjs-layers. Otherwise the code in github readme is not gonna work.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs-data/146)

### CODE REVIEW

**Comment by kangyizhang** [comment]
Good point, renamed the variables to `{xs_objects, ys_objects}`

**Comment by davidsoergel** [comment]
IIUC the {xs, ys} change is not released yet, so per the PR comment at the top our GitHub README is now out of sync.  However I think that is OK: the README should describe the code at head.  The only place where docs are pinned to released versions is https://js.tensorflow.org/api.

**Comment by kangyizhang** [comment]
Ah right I forgot about the readme doc will be updated even without
release. I will double check when will the feature be released and see if I
need to revert the readme doc.

Thanks for the notice.

David Soergel <notifications@github.com> 于 2019年2月26日周二 下午10:35写道：

**Comment by tafsiri** [comment]
@kangyizhang @davidsoergel, just so I understand have the keynames changed in the underlying object passed to map? Since this is an object destructure the names have to match what keys in the object passed in. I haven't been keeping track of this feature so just wanted to check.

**Comment by tafsiri** [comment]
looking at https://github.com/tensorflow/tfjs-data/blob/master/src/datasets/csv_dataset.ts#L266 i suspect it may need to be `xs` and `ys`.

**Comment by kangyizhang** [comment]
Yes, the names during object destructuring has to match the keys in the object passed in. Sent out https://github.com/tensorflow/tfjs-data/pull/152

**Comment by davidsoergel** [comment]
My fault, sorry!

**Pull request merged**
